### PR TITLE
Make it compile with Zig 0.11.0

### LINKED ISSUE #3: build: fails with zig `0.11.0-dev`
```console
/ztick/build.zig:12:19: error: no field or member function named 'standardReleaseOptions' in 'Build'
const mode = b.standardReleaseOptions();
            ~^~~~~~~~~~~~~~~~~~~~~~~
/zig/zig-linux-x86_64-0.11.0-dev.2725+4374ce51b/lib/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
```

it seems new `0.11.0-dev` API breaks the old builds, lets wait for `0.11` release.

### PR DESCRIPTION
**Pull request by mkrieger1**
This should fix #3

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM, Thanks for the PR
